services:
  - type: web
    name: slide-generator-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: RATE_LIMIT_PER_MINUTE
        value: 60
      - key: OUTPUT_DIR
        value: /opt/render/project/src/samples
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /api/v1/health
    autoDeploy: true 